name: Push to s3

on:
  push:
    paths:
      - swagger.json

jobs:
  push_to_s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: aws s3 rm s3://swagger-mintable/swagger.json
      - run: aws s3 cp ./swagger.json s3://swagger-mintable/
      - run: aws cloudfront create-invalidation --distribution-id E16T36QGU588JC --path "/*"
